server: https://bulk-data.smarthealthit.org/eyJlcnIiOiIiLCJwYWdlIjoxMDAwMCwiZHVyIjoxMCwidGx0IjoxNSwibSI6MTB9/fhir
auth_location: https://bulk-data.smarthealthit.org/auth/token
client_id: |
  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJfa2V5IjoiTFMwdExTMUNSVWRKVGlCUVZVSk1TVU1nUzBWWkxTMHRMUzBLVFVsSlFrbHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZQUTBGUk9FRk5TVWxDUTJkTFEwRlJSVUY2T0dsdGFEbEtVemhrVFhaNVMxVTRkVWhUTVFwRU1XazNkM3BEYWxaUVRqWkxPVGd3VkdsVmMxaEhLMVo2WnpWVk15czVTMDUwYlZsTk0wRk9TR3Q1VlRsVFdWaHlReTlJVTNVeU1EVklWMFIwVVVZMUNrMUhaVkJNVVRBMlVVNXBUVUpZWXpOcmQyNTVkV1JEUnpGck9XTnRaRTVMY1hsNlpHTjBWWFV2TjBkdVExUXJjbFJpUWk5blZtNWpSaTl3ZWtFMk5HWUtVVnBZUzJSdmRYZHNOVXhQVEhjemJuWnZRM0pRZVZoT2R6ZHdaV3BUYURSU05XZ3JSek1yTVZOMGJVWTFaWFJOYUZGWVVHWTJSbWc0V1hGdFlXSTRWd3BrVUM5YVVWQTROamRpZFhCNVpHMU5aMVpKVlZSa1lUSXpNVVJET1ZGc1VHaHRabWhGU2t0Qk5YSTVlbmhKZFcxalltcDJVMWxUTWpaRVMzazVNR1pEQ21wU1MxTjZXVEJIZW0xVFIxRXhaMjlwT1hOaFZESXpXSFUwVEZCT2FXaEtaRlJSTlU5WVJqaERkMmRGY21WQldWQlZWbGc0VVc1MlFWcE5OR2N5WWtNS1pIZEpSRUZSUVVJS0xTMHRMUzFGVGtRZ1VGVkNURWxESUV0RldTMHRMUzB0Q2c9PSIsImlzcyI6InVybjpmb29iYXIiLCJhY2Nlc3NUb2tlbnNFeHBpcmVJbiI6MTUsImlhdCI6MTUxNzE1NDMzMH0.MHOU8DVo40ZzmaeYgkmdFzTEOb50j-g8lurOSN0DFjo
client_url: urn:foobar
private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEogIBAAKCAQEAz8imh9JS8dMvyKU8uHS1D1i7wzCjVPN6K980TiUsXG+Vzg5U
  3+9KNtmYM3ANHkyU9SYXrC/HSu205HWDtQF5MGePLQ06QNiMBXc3kwnyudCG1k9c
  mdNKqyzdctUu/7GnCT+rTbB/gVncF/pzA64fQZXKdouwl5LOLw3nvoCrPyXNw7pe
  jSh4R5h+G3+1StmF5etMhQXPf6Fh8Yqmab8WdP/ZQP867bupydmMgVIUTda231DC
  9QlPhmfhEJKA5r9zxIumcbjvSYS26DKy90fCjRKSzY0GzmSGQ1goi9saT23Xu4LP
  NihJdTQ5OXF8CwgEreAYPUVX8QnvAZM4g2bCdwIDAQABAoIBAFQznbigtNgmmtCW
  lXqyYMUtUjmRNj8ww6uPsiSQz99NoMl16VMuJ0b++rythcNniV2m6CTw37QvjASg
  0pTBWhkRfmXlXFv25Rc57p15hJFkPaAPXRlBFJs1fTAR0A/yMByBXqwHAESs45Ib
  /gvZvfTX/Mn5ZcCmz0MmQWljvwHBVpxA1suzeGvpqLhDR7Re/63Ioxaln5salcuM
  zHIuyZMkizArdCetNq4uHUYKQdwyygfHC2RlLJm7qMX6DRRCpYY/Yh2YBQvw61G+
  e4476BxruB1g9tr6sPK3opAoRSU4vRyrmlGaby7Bm+dGeBl929guxpQMj4iJMXql
  MFUkGlECgYEA+ROpjMYLbJjBppYsWFsx8vfH89UcsMc/6BT9XisDr/78uJseH/FV
  t2izePAezZTB2Fk1PyYuaxqcFwVqqEjy3W1BxospRuFb80z1V+G45xejZmPfO2xH
  pJhmKURBn7nwadaNWgh1CPufwgXN5+bfe45QHwsW8pUPWdUwnbPJ+Y0CgYEA1Y8p
  mf/swGzn4MZ3x9Hht7TIA/b72zgPknC9jkZL7xa8hriXtXRCVfp2pZTeJKJTmXZs
  dEtP3W75eXtjMdWm3He+sv3PTzmBZQ7V+LzEI87ZkRMqY7kVMKhgKWyz5a5mIzcF
  UH/DA57MmTNYoTF2ANe+aHuy3OoS+E4nn0fKcRMCgYBJak8+bB1v6/KgXIFDpdWq
  LPil2Tn0rTYb/RvVRs52cK0i6K3Pcn32aokD65rYs7ETSPAV5fYmoZhCfNk8MwxK
  0epiUCBhgQluRE/IkILEssX55xQkWr0fOcBbB4BkSRUgzRmq4PVGKYykTrurT/St
  YXwiOk2QQPleXCVRRm4Q/QKBgGgVRzxUPEooifbGI/jSdQU46cbs6CEWuJgxtGEU
  J8wWM7ohW2dHi1EmKg9Xd9E5AC+qRP+E+R6+CH7JwTW3oISRI/NOumwtZcAgM+7v
  6VReazFGuwExYn99gKiP3znQ/tyo40Exk5U/Hw6HtOmTFqUggR+hMjJzLt2wEaWS
  srrbAoGAAtUXXlQvrjuqb32DgMeekxFIh6Dv8HfMW7iLjmojHf0LjakyZ4wqfzKk
  L+cVKJCVlswpiMeDOsjkOQCfTl5p1gKM5tkIxAxAeNvFcnd4gb1yjMV22waGjsQ+
  qSKTouCQCZZ2IyKCZTga9Qty4zv8I2FO/QcZxeciAebYjwYdnRk=
  -----END RSA PRIVATE KEY-----
